### ISSUE TITLE
undefined 函数兼容数组类型字段

### ISSUE THREAD

**Issue by vincentlauvlwj** [kotlin-orm/ktorm-ksp#13]
目前 `undefined` 函数没有兼容数组类型，针对数组类型 `arrayClass`，考虑使用 `java.lang.reflect.Array.newInstance(arrayClass.componentType, 0)` 创建一个长度为 0 的空数组

**Comment by lookup-cat** [comment]
这个也已经有啦
https://github.com/kotlin-orm/ktorm-ksp/blob/master/ktorm-ksp-api/src/main/kotlin/org/ktorm/ksp/api/EntityUtil.kt

**Comment by vincentlauvlwj** [comment]
哈哈，nice
