### ISSUE TITLE
generated code 怎么让IDEA 识别到？

### ISSUE THREAD

**Issue by jianweidai** [kotlin-orm/ktorm-ksp#15]
我的配置

```
id("com.google.devtools.ksp") version("1.6.21-1.0.5")

//orm
implementation("org.ktorm:ktorm-core:3.5.0")
implementation("org.ktorm:ktorm-jackson:3.5.0")
implementation("org.ktorm:ktorm-support-postgresql:3.5.0")
implementation("org.ktorm:ktorm-ksp-api:1.0.0-RC3")
ksp("org.ktorm:ktorm-ksp-compiler:1.0.0-RC3")

kotlin {
	sourceSets.main {
		kotlin.srcDir("build/generated/ksp/main/kotlin")
	}
	sourceSets.test {
		kotlin.srcDir("build/generated/ksp/test/kotlin")
	}
}
```

自动生成的类确实是在build/generated/ksp/main/kotlin。但是这个类IDEA是识别不到的，在程序中引用不到。
<img width="399" alt="image" src="https://user-images.githubusercontent.com/7667765/183847680-7d981092-bc89-4102-8e31-0f0a986b154b.png">

请问是我的配置有问题吗 还是？

**Comment by lookup-cat** [comment]
看上面的配置没有什么问题，你可以清除一下idea的缓存试试。 
如果还是不行，可以下载本项目的代码进行构建，然后看IDEA能不能识别```ktorm-ksp-example```模块的生成代码，如果还是不识别那说明可能是IDEA版本问题

**Comment by jianweidai** [comment]
是我本地的问题，按照配置已经可以自动生成代码，并被识别到了。
