### ISSUE TITLE
生成的 table 类, 希望可以不是单例的, 或者可以通过生成配置动态选择

### ISSUE THREAD

**Issue by zuisong** [kotlin-orm/ktorm-ksp#2]
[自连接查询与表别名](https://www.ktorm.org/zh-cn/joining.html#%E8%87%AA%E8%BF%9E%E6%8E%A5%E6%9F%A5%E8%AF%A2%E4%B8%8E%E8%A1%A8%E5%88%AB%E5%90%8D)

ktorm 文档有介绍这样做的好处

![image](https://user-images.githubusercontent.com/19145952/176108456-66af2a74-9907-4cbb-bc4f-b5b64795826b.png)

**Comment by zuisong** [comment]
这个代码生成器很棒, 几乎满足了我的所有期望, 感谢贡献👍

**Comment by vincentlauvlwj** [comment]
这个建议很好

**Comment by lookup-cat** [comment]
感谢提议，后续会加上

**Comment by lookup-cat** [comment]
已合并pr #5
