### ISSUE TITLE
针对 interface 的实体对象，建议生成伪构造函数、componenntN、copy，支持 data class 一样的使用体验

### ISSUE THREAD

**Issue by vincentlauvlwj** [kotlin-orm/ktorm-ksp#3]
比如这样的实体类

```kotlin
@Table
interface Student : Entity<Student> {
    var id: Int
    var name: String
    var age: Int
}
```

生成代码：

```kotlin
fun Student(id: Int = 0, name: String = "", age: Int = 0): Student {
    val entity = Entity.create<Student>()
    entity.id = id
    entity.name = name
    entity.age = age
    return entity
}
```

这样使用起来就像真正的 data class 一样：

```kotlin
val s = Student(id = 1, name = "vince")
database.students.add(s)
```

**Comment by lookup-cat** [comment]
参数的默认值要怎么处理呢. 非空基础类型还好. 如果是可空基础类型那么默认值是null?  还有联表的引用类型, 要不要也生成默认值呢 这也是个问题

**Comment by vincentlauvlwj** [comment]
按照这里提到的默认值规则就好 https://www.ktorm.org/zh-cn/entities-and-column-binding.html#%E5%85%B3%E4%BA%8E-Entity-%E6%8E%A5%E5%8F%A3

**Comment by vincentlauvlwj** [comment]
代码在这里 https://github.com/kotlin-orm/ktorm/blob/master/ktorm-core/src/main/kotlin/org/ktorm/entity/Reflections.kt#L53

**Comment by lookup-cat** [comment]
上述默认值规则中最后一项
> 未识别类型，调用其无参构造函数创建一个对象并返回，如果没有无参构造函数，则抛出异常

在ktorm中这样做没什么问题. 只有在实体没有此属性值, 并尝试获取该属性值时会抛出异常.
但是在ksp中并不能这样直接抛出异常生成代码失败, 不生成默认值应该是更合理的.

同时可以考虑更多类型的默认值, 例如LocalDate、BigDecimal等等, 像这些类型的默认值放在ktorm中不太合理, 容易引起歧义. 然而在ksp中作为创建对象的默认值, 是比较直观合理的

**Comment by lookup-cat** [comment]
总结一下默认值规则大概如下:
- 如果是可空, 默认值为null
- 不可空, 尝试获取预设的类型默认值
- 获取不到预设默认值, 如果类型是接口实体类型, 使用Entity.create()创建对象(或者判断ksp是否有生成该类型的无参构造函数, 如果有就调用. 这一步可能会比较复杂). 如果是普通类并且有无参构造, 直接调用无参构造
- 不符合上述所有规则, 不生成默认值

**Comment by vincentlauvlwj** [comment]
> 但是在ksp中并不能这样直接抛出异常生成代码失败, 不生成默认值应该是更合理的

在生成代码的时候抛异常确实不合适，我觉得更好的方式是让代码正常生成，但是在调用的时候、运行时抛异常

> 同时可以考虑更多类型的默认值, 例如LocalDate、BigDecimal等等

这个不建议哈，默认值的规则我建议和 ktorm 原有的规则一直，如果在这里有例外，就相当于存在两套默认值规则，容易让用户产生疑惑

> 或者判断ksp是否有生成该类型的无参构造函数, 如果有就调用. 这一步可能会比较复杂

这个也不建议，以下面的 `Employee` 实体类为例，里面包含一个 `manager` 属性也是 `Employee` 类型，如果使用这个规则，容易产生无限递归导致内存溢出，这个异常信息对用户十分不友好，直接调用 `Entity.create` 创建空对象即可

```kotlin
interface Employee : Entity<Employee> {
    val id: Int
    var name: String
    var job: String
    var manager: Employee
    var hireDate: LocalDate
    var salary: Long
    var department: Department
}
```

**Comment by vincentlauvlwj** [comment]
> 不符合上述所有规则, 不生成默认值

我觉得，无论如何每个属性都应该生成默认值，只不过这个默认值不是在代码生成的过程中直接产生，而是在运行的时候生成，针对不符合规则的，运行时抛出异常即可

比如

```kotlin
fun Student(
    id: Int = defaultValue<Int>(), 
    name: String = defaultValue<String>(), 
    age: Int = defaultValue<Int>()
): Student {
    // ...
}
```

**Comment by lookup-cat** [comment]
> > 不符合上述所有规则, 不生成默认值
> 
> 我觉得，无论如何每个属性都应该生成默认值，只不过这个默认值不是在代码生成的过程中直接产生，而是在运行的时候生成，针对不符合规则的，运行时抛出异常即可
> 
> 比如
> 
> ```kotlin
> fun Student(
>     id: Int = defaultValue<Int>(), 
>     name: String = defaultValue<String>(), 
>     age: Int = defaultValue<Int>()
> ): Student {
>     // ...
> }
> ```

👍忘了还有这种操作了

**Comment by lookup-cat** [comment]
仔细一想这样会产生没必要的性能开销不说, 重点在对于不识别的类型, 运行时调用会直接抛出异常, 这种异常是不直观的也是不友好的.  既然这个默认值调用了会报错, 那我认为还不如干脆不给默认值, 需要强制传参更友好一些

**Comment by lookup-cat** [comment]
其实感觉要考虑这么多种情况, 还要保留原本的默认值规则, 我感觉难以生成好用的构造函数.
也许让interface的实体变的像data class, 是不太好的. 不如换个角度想, 生成这种函数是不是好用一点呢

```kotlin
@Table
public interface Student : Entity<Student> {
    @PrimaryKey
    public var id: Int?
    public var name: String
    public var age: Int

    // 等于省去了这一行代码
    // public companion object : Entity.Factory<Student>()
}


// 生成代码
public inline fun Student(block: Student.() -> Unit): Student {
    val entity = Entity.create<Student>()
    block(entity)
    return entity
}

public fun main() {
    val student = Student { 
        name = "name"
        age = 10
    }
}
```

**Comment by lookup-cat** [comment]
生成伪构造函数, 我觉得不好用的地方在于
- 可空类型要不要生成默认值难以抉择, 如果要生成值并且实体有自增主键, 那么每次调用构造函数都得设置主键为null. 如果不生成值, 那用起来感觉好像也不怎么便捷.
- 不可识别类型的默认值如何处理, 如果是运行时生成, 那么这个构造函数其实用起来跟伴生对象继承Entity.Factory的形式是差不多的. 如果是不生成, 改成必传参数, 由于还要考虑默认值规则的因素, 一旦用了BigDecimal、LocalDateTime等这种类型的参数,就得是必传的.这样并没有享受到ksp自动生成代码的好处, 我不觉得这种构造函数比Entity.Factory强在哪里

综上所述, 我觉得interface实体难以生成好用的构造函数, 不如干脆我们只做一个简化伴生对象继承Entity.Factory的操作. 想要简单易用的实体类型就干脆用data class

**Comment by vincentlauvlwj** [comment]
你说的问题本质上是因为我们生成的伪构造函数无论如何都会对实体对象的属性赋值，比如说这两段代码

使用初始化块：

```kotlin
val student = Student {
    name = "mary"
    birthday = LocalDate.now()
}
```

使用伪构造函数：

```kotlin
val student = Student(name = "mary", birthday = LocalDate.now())
```

表面上这两段代码的含义是一样的，但实际上，使用初始化块的代码，只会给 `name` 和 `age` 两个属性赋值，但使用伪构造函数的代码，除了这两个属性之外，还会给所有的属性赋上一个默认值，这就造成了你说的还需要手动把主键设置为 null 的问题

其实这个问题在我提出这个 issue 的时候就注意到了，只不过当时没有多想，今天重新整理了一下思路，想到一个新的方案，你再看看

我们以这个实体类为例：

```kotlin
@Table
public interface Student : Entity<Student> {
    public var id: Int
    public var name: String?
    public var birthday: LocalDate?
}
```

生成代码：

```kotlin
/**
 * 单例对象，作为参数的默认值，表示用户没有对参数赋值
 */
public object Undefined

/**
 * 生成的伪构造函数，所有参数的类型都是 Any?，默认值都是 Undefined
 */
public fun Student(id: Any? = Undefined, name: Any? = Undefined, birthday: Any? = Undefined): Student {
    val entity = Entity.create<Student>()

    if (id !== Undefined) {
        if (id is Int) {
            entity.id = id
        } else {
            throw IllegalArgumentException("`id` should be typed of Int but actually ${id?.javaClass?.name}")
        }
    }

    if (name !== Undefined) {
        if (name is String?) {
            entity.name = name
        } else {
            throw IllegalArgumentException("`name` should be typed of String? but actually ${name?.javaClass?.name}")
        }
    }

    if (birthday !== Undefined) {
        if (birthday is LocalDate?) {
            entity.birthday = birthday
        } else {
            throw IllegalArgumentException("`birthday` should be typed of LocalDate? but actually ${birthday?.javaClass?.name}")
        }
    }

    return entity
}
```

**Comment by vincentlauvlwj** [comment]
我们的关键就是要判断出用户到底有没有主动给属性赋值。对于非空类型的属性还好，我们可以用 null 作为参数默认值，代表用户没有赋值。但是对于可空类型就不好办了，属性的值本身也可以是 null，用户完全可以手动给属性赋值为 null

在 Ktorm 中，一个属性的值为 null 与“未赋值”其实有着微妙的区别，比如：

```kotlin
val student = Student()
student.name = null
database.students.add(student)
```

这段代码会生成一条 insert 语句，里面只包含赋值的字段 `name` (即使赋值为 null)，不包含其他未赋值字段：

```sql
insert into student (name) values (NULL)
```

所以在这个方案里面，我们需要一个单例对象 `Undefined`，用来表示“未赋值”的状态，当参数的值为 `Undefined` 时，不会给对应的属性赋值，这样就保证了伪构造函数的行为与初始化块完全一致

但是这个方案也有个小问题，我们必须把参数的类型设置为 `Any?`，这是因为 Kotlin 不支持 `String? | Undefined` 这样的或类型，只能稍微妥协一下。把参数设置为 `Any?` 可能会让一些编译期的检查失效，但是我觉得问题不算太大，我们可以在生成的代码里面做类型检查，并且抛出完善的异常信息

**Comment by vincentlauvlwj** [comment]
使用这个方案的伪构造函数，与初始化块相比，我更倾向于前者。在实践中，使用初始化块经常会遇到命名冲突的问题，因此我自己在使用 Ktorm 的时候，即使会给实体类添加 companion object，我也几乎不会使用初始化块来创建实体对象，比如：

```kotlin
public fun createStudent(name: String, birthday: LocalDate) {
    val student = Student {
        this.name = name
        this.birthday = birthday
    }
    
    database.students.add(student)
}
```

在这个例子里面，由于存在命名冲突，我们不得不在初始化块里面使用 `this` 区分，这实在说不上方便。而使用伪构造函数的体验，除了参数的类型是 `Any?` 之外，几乎和真正的 data class 一模一样

**Comment by vincentlauvlwj** [comment]
除了伪构造函数之外，我们还可以生成 `componentN` 和 `copy` 函数，以支持 data class 常用的解构和复制功能，比如：

```kotlin
public operator fun Student.component1(): Int {
    return id
}

public operator fun Student.component2(): String? {
    return name
}

public operator fun Student.component3(): LocalDate? {
    return birthday
}

public fun Student.copy(id: Int = this.id, name: String? = this.name, birthday: LocalDate? = this.birthday): Student {
    return Student(id, name, birthday)
}
```

使用示例：

```kotlin
public fun main() {
    // 构造
    val s = Student(id = 123, name = "vince", birthday = LocalDate.now())
    // 解构
    val (id, name, birthday) = s
    // 复制
    val s2 = s.copy(name = "mary")
}
```

有了伪构造函数、`componentN`、`copy` 的支持，我们的实体类的使用体验几乎已经完全跟 data class 一模一样了

**Comment by lookup-cat** [comment]
使用Undefined作为默认值, 这会让人感觉在写js一样, 几乎等于失去了编译时类型检查, 尽管能解决是否要赋值默认值的问题, 但我觉得很得不偿失了, 要是这是ts语言那我会赞同这种做法. 在kotlin上我觉得这个副作用太大了, 我宁愿用Entity.Factory的写法:```this.name = name``` 类型提示还是很重要不能丢弃

或者也可以用Builder的写法
```kotlin
Student.builder()
    .name(name)
    .age(age)
    .build()
```
这是稍微要啰嗦一点, 但相比Undefined的方案的副作用, 我觉得Builder的副作用就小多了
当然这个builder也可以稍微加以改进简化语法
```kotlin
public class StudentBuilder {
    public val student: Student = Student()
    public fun id(value: Int?) {
        student.id = value
    }

    public fun name(value: String) {
        student.name = value
    }

    public fun age(age: Int) {
        student.age = age
    }   
}

public fun buildStudent(action: StudentBuilder.() -> Unit): Student {
    val builder = StudentBuilder()
    action(builder)
    return builder.student
}
```
调用起来就是这样, 赋值字段不再需要加个this
```kotlin
val name = "name"
val age = 10
val student: Student = buildStudent {
    name(name)
    age(age)
}
```
这是我能想到最简洁的写法了. 只不过这个buildStudent是个顶级函数, 可能会污染编译器提示, 改成伴生对象里的invoke方法可能好一点

**Comment by lookup-cat** [comment]
又想到一种方式
```kotlin
public sealed class Value<T>
public object Undefined : Value<Nothing>()
public class ActualValue<T>(public val value: T) : Value<T>()

public inline fun <reified T> value(value: T): ActualValue<T> = ActualValue(value)

public fun Student(
    id: Value<out Int?> = Undefined,
    name: Value<out String> = Undefined,
    age: Value<out Int> = Undefined
): Student {
    return Student {
        if (id is ActualValue) {
            this.id = id.value
        }
        if (name is ActualValue) {
            this.name = name.value
        }
        if (age is ActualValue) {
            this.age = age.value
        }
    }
}

public fun main() {
    val student = Student(name = value("name"))
}
```

毕竟没有联合类型也没有c#的隐式类型转换, 还要保留有编译器的类型提示, 就只能这样了

**Comment by vincentlauvlwj** [comment]
使用 builder 让我有种回到 Java 的感觉，一点也不 Kotlin style；sealed class 的方案我其实也考虑过，但是传入的每个值都要用 `value()` 包装一次实在是麻烦；从代码美观程度来说，我觉得还是用 `Any?` 的方案更好，而且能完全模拟出 data class 的用法，看起来毫无违和感...

我觉得为了代码的美观，这个地方的静态类型检查是可以妥协的，没有必要看到 `Undefined` 这样的字眼就害怕，这里的问题没有 js 里面那么严重。首先 js 是弱类型的，我们虽然在这里没有静态类型检查，但仍然是强类型的，而且我们并不是不检查类型，我们只不过是把这个检查推迟到运行时，通过完善的异常信息，用户也能很快定位到问题

![image](https://user-images.githubusercontent.com/10897214/177103883-ae209027-9937-4353-b86d-969d4287e17a.png)

**Comment by lookup-cat** [comment]
其实就跟python那种差不多了 只是我觉得缺少了idea的提示会增加心智负担， 尤其你表数量稍微多一点记不住类型， 用的时候就得经常去看每个列对应类型。。 我感觉这用起来并不比EntityFactory的方便， 其实看上去代码简洁了 用起来并不简单。

要做到最好的效果应该是像下面这样
```kotlin
// 定义一个入口
fun User(
    id: Int? = throw Exception(),
    name: String = throw Exception(),
    age: Int = throw Exception()
) {
    // ...
}

// 调用时
User(name="name")

// 等同于下面这个效果
val user = Entity.create<User>()
user.name = name
```
光靠ksp肯定做不到这样，但是我发现kotlin的编译插件可以实现这种修改方法bytecode的能力，也许它能帮助我们实现这种黑魔法，感觉可以往这个方向研究一下

**Comment by lookup-cat** [comment]
kotlin的编译器插件文档不多，看到一个比较详细的可以参考一下https://resources.jetbrains.com/storage/products/kotlinconf2018/slides/5_Writing%20Your%20First%20Kotlin%20Compiler%20Plugin.pdf

**Comment by vincentlauvlwj** [comment]
哈哈，我之前也考虑过编译器插件，也找到了这个文档，只不过一直没有真正实践，要是有了编译器插件，不止这个 issue，甚至 ktorm 都不需要 `eq`, `gt`, `lt` 这些运算符函数了，直接换成 `==`, `>`, `<` 都可以实现...

**Comment by lookup-cat** [comment]
主要上面这几个方案我都觉得不行，各有各的缺点😂
用编译器插件的话来改bytecode就很蛋疼，这个问题不简单，我尽量研究下能不能实现吧。。

**Comment by vincentlauvlwj** [comment]
为了这个问题去研究编译器插件 ROI 有点低了，就算编译器支持了，可能在 IDE 集成方面还会遇到问题...我觉得还是不要那么强迫症，`Any?` 的方案就算不完美，也可以作为临时的选择，后面如果通过编译器插件完美实现、或者 Kotlin 什么时候支持联合类型和隐式转换，还可以不改代码无缝迁移；如果使用 sealed class 的方案，后面迁移还需要用户改代码

**Comment by lookup-cat** [comment]
OK，那就暂且先用Any?的方案了。 毕竟编译器插件就算能实现，一时半会也做不出来

**Comment by vincentlauvlwj** [comment]
`Any?` 的方案有个稍微优化的版本：

```kotlin
/**
 * 使用函数而不是单例 object 来定义 undefined，实际值为 Unit
 */
public fun <T> undefined(): Unit = Unit

/**
 * 参数默认值改成 undefined<T>()
 */
public fun Student(
    id: Any? = undefined<Int>(),
    name: Any? = undefined<String?>(),
    birthday: Any? = undefined<LocalDate?>()
): Student {
    // 函数体略
}
```

实际使用的时候，虽然还是没有静态检查，但是 IDE 可以提示出参数的类型：

![image](https://user-images.githubusercontent.com/10897214/177125912-ee694862-1d19-4418-a6ef-1197ad62684a.png)

**Comment by lookup-cat** [comment]
这个倒可以，心智负担大大减小

**Comment by vincentlauvlwj** [comment]
还有一个方案，使用 `Unsafe` 黑科技为每个类型创建一个空实例作为默认值，`allocateInstance` 方法可以无视构造函数、跳过类初始化逻辑，直接创建一个类的空实例

这样我们就可以把参数都定义成对应的类型，而不是 `Any?`

```kotlin
@PublishedApi
internal val undefinedValues: ConcurrentMap<Class<*>, Any> = ConcurrentHashMap()

public inline fun <reified T> undefined(): T? {
    val loader = { cls: Class<*> ->
        // 以下获取 Unsafe 的代码只适用 JDK 1.8，JDK 9 及以上需要另外适配
        val field = Unsafe::class.java.getDeclaredField("theUnsafe")
        field.isAccessible = true
        (field.get(null) as Unsafe).allocateInstance(cls)
    }

    return undefinedValues.computeIfAbsent(T::class.java, loader) as T
}

public fun Student(
    id: Int? = undefined(),
    name: String? = undefined(),
    birthday: LocalDate? = undefined()
): Student {
    val entity = Entity.create<Student>()

    if (id !== undefined<Int>()) {
        entity.id = id ?: error("`id` should not be null.") // 必须在运行时进行非空校验
    }

    if (name !== undefined<String>()) {
        entity.name = name
    }

    if (birthday !== undefined<LocalDate>()) {
        entity.birthday = birthday
    }

    return entity
}
```

这个方案也有很明显的缺点：

- 属性类型为抽象类或接口时不适用，比如 `Number`，调用 `allocateInstance` 时会抛出异常，除非我们在运行时利用字节码生成，动态创建一个实现类（这个有一点工作量，但不会太难）
- 针对非空的基础类型比如 `Int`，参数类型也不得不定义成 `Int?`，这是为了避免编译后自动拆箱为 `int`，影响 `id !== undefined<Int>` 的判断逻辑，这就导致我们这个方案虽然保证了静态类型校验，但非空校验仍然需要在运行时进行

**Comment by lookup-cat** [comment]
非空基础类型这个在kotlin1.7上倒是有个骚操作可以强行避免自动拆箱
```kotlin
@Suppress("FINAL_UPPER_BOUND", "UNCHECKED_CAST")
public fun <Id : Int?> Student(
    id: Id & Any = undefined<Int?>() as (Id & Any),
    name: String? = undefined(),
    age: Int? = undefined()
): Student {
    val entity = Entity.create<Student>()

    if (id !== undefined<Int>()) {
        entity.id = id
    }

    if (name !== undefined<String>()) {
        entity.name = name
    }

    if (age !== undefined<Int?>()) {
        entity.age = age
    }

    return entity
}
```
这样id就是Integer类型了

**Comment by lookup-cat** [comment]
哦不对，这种方式调用时不传id参数，就得手动写泛型实参，```Student<Int>()``` 那用普通的泛型方法也能做到了，这样写不太优雅

**Comment by vincentlauvlwj** [comment]
嗯，我感觉 `Unsafe` 这个方案应该是比较完美的一个了，虽然字节码生成的工作量可能会多一点，用户使用起来唯一的问题就只剩下非空校验了

**Comment by lookup-cat** [comment]
这个copy方法也有个问题
```kotlin
public fun Student.copy(id: Int = this.id, name: String? = this.name, birthday: LocalDate? = this.birthday): Student {
    return Student(id, name, birthday)
}
```
参数这样写也会导致给所有的属性生成默认值，正确的处理应该是获取```EntityImplementation.values```属性，判断有没有这个值，没有就调用undefined方法赋值。 但是这个类是internal类，这样的话貌似只能反射处理了🤔

**Comment by vincentlauvlwj** [comment]
ktorm 3.5.0 开放了这个 API，不需要用反射 https://www.ktorm.org/api-docs/org.ktorm.entity/-entity-extensions-api/index.html

**Comment by vincentlauvlwj** [comment]
或者把 `copy` 方法改成这样你看行不行：

```kotlin
public fun Student.copy(
    id: Int? = undefined(), 
    name: String? = undefined(), 
    birthday: LocalDate? = undefined()
): Student {
    return Student(
        id = if (id === undefined<Int>()) this.id else id,
        name = if (name === undefined<String>()) this.name else name,
        birthday = if (birthday === undefined<LocalDate>()) this.birthday else birthday
    )
}
```

**Comment by lookup-cat** [comment]
哦原来已经开放了，那就简单了

**Comment by vincentlauvlwj** [comment]
我重新梳理了一下，ktorm 本身已经有一个通用的 `Entity.copy` 函数，这个方法是深复制，不仅会复制所有属性，还会复制内部的状态跟踪信息，我想我们这次生成的 `copy` 函数应该保持一致的行为，否则会让用户感到困惑，所以生成的代码改成这样你看如何？

```kotlin
public fun Student.copy(
    id: Int? = undefined(),
    name: String? = undefined(),
    birthday: LocalDate? = undefined()
): Student {
    val entity = this.copy()

    if (id !== undefined<Int>()) {
        entity.id = id ?: error("`id` should not be null.") // 必须在运行时进行非空校验
    }

    if (name !== undefined<String>()) {
        entity.name = name
    }

    if (birthday !== undefined<LocalDate>()) {
        entity.birthday = birthday
    }

    return entity
}
```

**Comment by lookup-cat** [comment]
刚提交完这一块的代码才看到😂 
考虑到深拷贝和状态跟踪的话, 确实用这种方式更适合些

**Comment by lookup-cat** [comment]
undefined创建代理实例, 试了一下几个jdk版本的Unsafe好像都没啥问题, 倒是cglib对高版本(17试了不行)或者部分jdk的兼容性不太好

**Comment by lookup-cat** [comment]
v1.0.0-RC3已支持
