### ISSUE TITLE
关于自定义生成器的使用疑问

### ISSUE THREAD

**Issue by llh4github** [kotlin-orm/ktorm-ksp#8]
看了自定义生成器的文档后简单试了下，似乎只支持将自定义生成器放在单独的模块中使用。
对于一些简单的小项目来说，这样做有点复杂了。不知道能否提供配置自定义类全限定名之类的方法简化自定义生成器的使用？

**Comment by lookup-cat** [comment]
由于ksp的实现限制，做不到这一点。
借用官方的一张图，kotlin的编译过程大概如下
![1958E221-48FB-4B29-B9EC-8AF2186098FD](https://user-images.githubusercontent.com/45026715/177909559-5b227a1b-843b-4a17-af98-a558bbd4922f.png)

分为frontend、backend两个步骤
- frontend 主要是做一些语法检查、解析语法树的工作
- backend 通过语法树生成中间代码、jvm bytecode / js

ksp插件的运行过程发生在frontend这一步骤，还没有真正将项目里的代码编译成bytecode，因此此时是执行不了项目里的代码的。

**Comment by vincentlauvlwj** [comment]
@lookup-cat 借助 gradle 实现插件化，理论上是可以做到的，用户只需要把自己的插件写在 `buildSrc` 里面，而不是项目代码里面

**Comment by lookup-cat** [comment]
> @lookup-cat 借助 gradle 实现插件化，理论上是可以做到的，用户只需要把自己的插件写在 `buildSrc` 里面，而不是项目代码里面

那就跟单独创建一个模块没多大区别了倒是
